---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-cloudflared
  namespace: wp
spec:
  selector:
    matchLabels:
      app: blog-cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: blog-cloudflared-credentials
      - name: config
        configMap:
          name: blog-cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-cloudflared-config
  namespace: wp
data:
  config.yaml: |
    tunnel: cdb02991-80a4-4993-92cb-802b9e4ce269
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: blog.debene.dev
      service: http://wordpress-frenzy:80
      originRequest:
        originServerName: blog.debene.dev
    - service: http_status:404
