apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: 
            - "cloudflared"
            - "tunnel"
            - "run"
            - "70598e0b-4a72-49bd-a88b-f6d7045c63ba"
          env:
            - name: TUNNEL_ORIGIN_CERT
              value: /etc/cloudflared/cert.pem
          volumeMounts:
            - name: cloudflared-secret-vol
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-secret-vol
          projected:
            sources:
              - secret:
                  name: cloudflared-secret
              - secret:
                  name: cloudflared-cert-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: wp
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 80
