apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: [ "cloudflared", "tunnel", "run", "70598e0b-4a72-49bd-a88b-f6d7045c63ba" ]  # Tunnel ID passed here
          env:
            - name: TUNNEL_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: tunnel-secret  # Your tunnel secret should be in the Kubernetes secret.
          volumeMounts:
            - name: cloudflared-cert
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared-cert
          secret:
            secretName: cloudflared-cert-secret  # Ensure this secret contains the certificate
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: wp
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 80