apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: 
            - "/bin/sh"
            - "-c"
          args:
            - |
              echo '{
                "AccountTag": "your_account_tag",
                "TunnelID": "70598e0b-4a72-49bd-a88b-f6d7045c63ba",
                "TunnelSecret": "'$(cat /etc/cloudflared/tunnel-secret)'",
                "TunnelName": "wordpress-tunnel"
              }' > /etc/cloudflared/credentials.json && 
              cloudflared tunnel run --credentials-file /etc/cloudflared/credentials.json
          volumeMounts:
            - name: cloudflared-creds
              mountPath: /etc/cloudflared
              readOnly: true
            - name: cloudflared-config
              mountPath: /tmp/config
      volumes:
        - name: cloudflared-creds
          secret:
            secretName: cloudflared-secret
            items:
              - key: tunnel-secret
                path: tunnel-secret
        - name: cloudflared-config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: wp
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 80
