apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflared-secret
                  key: tunnel-id
            - name: TUNNEL_CRED_FILE
              value: /etc/cloudflared/creds/credentials.json
          volumeMounts:
            - name: cloudflared-creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cloudflared-cert
              mountPath: /etc/cloudflared/cert
              readOnly: true
      volumes:
        - name: cloudflared-creds
          secret:
            secretName: cloudflared-secret
            items:
              - key: tunnel-secret
                path: credentials.json
        - name: cloudflared-cert
          secret:
            secretName: cloudflared-cert-secret
            items:
              - key: cert.pem
                path: cert.pem
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: wp
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 80
