apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          command: 
            - "/bin/sh"
            - "-c"
          args:
            - |
              cp /etc/cloudflared/cert/cert.pem /etc/cloudflared/cert.pem &&
              echo '{
                "AccountTag": "b16a8a579828f17deecf2f0da24752",
                "TunnelID": "70598e0b-4a72-49bd-a88b-f6d7045c63ba",
                "TunnelSecret": "'$(cat /etc/cloudflared/creds/tunnel-secret)'",
                "TunnelName": "wordpress-tunnel"
              }' > /etc/cloudflared/credentials.json && 
              cat /etc/cloudflared/credentials.json &&
              cloudflared tunnel run --credentials-file /etc/cloudflared/credentials.json
          env:
            - name: TUNNEL_ORIGIN_CERT
              value: /etc/cloudflared/cert.pem
          volumeMounts:
            - name: cloudflared-creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cloudflared-cert
              mountPath: /etc/cloudflared/cert
              readOnly: true
      volumes:
        - name: cloudflared-creds
          secret:
            secretName: cloudflared-secret
            items:
              - key: tunnel-secret
                path: tunnel-secret
        - name: cloudflared-cert
          secret:
            secretName: cloudflared-cert-secret
            items:
              - key: cert.pem
                path: cert.pem
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  namespace: wp
spec:
  selector:
    app: cloudflared
  ports:
    - port: 80
      targetPort: 80
