apiVersion: v1
kind: Secret
metadata:
  name: blog-credentials
type: Opaque
stringData:
  blog-credentials.json: |
    {
      "xmlrpc_url": "https://your-blog.com/xmlrpc.php",
      "username": "your_username",
      "password": "YOUR_APPLICATION_PASSWORD"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "us-west-2"
